texts:
  1:
    # Original text pattern.
    pattern: ":\\)"
    # Text to replace.
    newtext: "❤"
    # Permission of the message if null, no permission.
    permission: chatreplacer.hearth
  2:
    pattern: ":note:"
    newtext: "♪"
    permission: chatreplacer.note
  3:
    pattern: ":natural:"
    newtext: "♮"
    permission: chatreplacer.natural
  4:
    pattern: ":check:"
    newtext: "✔"
    permission: chatreplacer.check
